# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: http://jabber.oppophp.com
date_format: "ordinal"
title: Jabber
subtitle: "全汝形，抱汝生，勿使汝思虑营营！"
description: "Jabber的个人博客"
keywords: php,laravel,thinkphp,vagrant,jabber,c,java,docker,nodejs,python,ruby,golang,lua,webpack,gulp,grunt,reactjs,vuejs,angularjs,jquery
favicon: /favicon.ico
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: Jabber
organization: Trendsoft, Inc.
organization_url: https://www.trendsoft.org
location: Wuhan, China
email: 2898117012@qq.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

# ---------------- #
#      Socials     #
# ---------------- #
github_username: 2898117012
# douban_username: freedim
# facebook_username: mzlogin
# weibo_username: mzlogin
# zhihu_username: mzlogin
# twitter_username: mzlogin

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, duoshuo
comments_provider: duoshuo
# !!!重要!!! 请修改下面两个用户名为你自己申请的
# !!!Important!!! Please modify usernames below to yours
duoshuo_username: jabber
# disqus_username: mzlogin
# 在使用 disqus 的时候可点击显示多说评论框
lazy_load_duoshuo: false

# ---------------- #
#    Analytics     #
# ---------------- #
#google:
#    analytics_id: UA-84290351-1

# ---------------- #
#      Datas       #
# ---------------- #
skill_software_keywords: [PHP,Lavel,Java,Nodejs,Ruby,Python,Lua,Golang,C++, Python, Design Patterns,UML]
skill_mobile_app_keywords: [Android,IOS,HTML5, Reverse Engineering]
skill_windows_keywords: [Win32 SDK, DuiLib, WTL, COM, WinDbg]
public_repositories: []
contribute_repos: ['2898117012/c-lang-demo']